name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: where are we
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: try a different die
      run: cd WebSiteMeta
    - name: Install dependencies
      run: dotnet restore ./websitemetascraper/websitemeta/websitemeta.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
